// Code generated by hand from openapi.StrictServerInterface. DO NOT EDIT MANUALLY.
//
// openapi.yaml に定義済みだが未実装の操作をまとめて 501 にする。
// Server がこれを埋め込むことで、実装済みの操作だけを上書きすれば足りる状態を保つ。
// openapi.yaml に操作が増えると Server がインターフェースを満たさなくなりビルドが落ちるので、
// 「仕様に足したのにサーバ側が追随していない」状態は CI で検出できる。
package handler

import (
	"context"

	"github.com/Kenyan822/physique-analytics/api/gen/openapi"
)

// Unimplemented はすべての操作を 501 Not Implemented で返す。
type Unimplemented struct{}

func (Unimplemented) GetHealth(_ context.Context, _ openapi.GetHealthRequestObject) (openapi.GetHealthResponseObject, error) {
	return nil, notImplemented("GetHealth")
}

func (Unimplemented) ListExercises(_ context.Context, _ openapi.ListExercisesRequestObject) (openapi.ListExercisesResponseObject, error) {
	return nil, notImplemented("ListExercises")
}

func (Unimplemented) CreateExercise(_ context.Context, _ openapi.CreateExerciseRequestObject) (openapi.CreateExerciseResponseObject, error) {
	return nil, notImplemented("CreateExercise")
}

func (Unimplemented) DeleteExercise(_ context.Context, _ openapi.DeleteExerciseRequestObject) (openapi.DeleteExerciseResponseObject, error) {
	return nil, notImplemented("DeleteExercise")
}

func (Unimplemented) GetExercise(_ context.Context, _ openapi.GetExerciseRequestObject) (openapi.GetExerciseResponseObject, error) {
	return nil, notImplemented("GetExercise")
}

func (Unimplemented) UpdateExercise(_ context.Context, _ openapi.UpdateExerciseRequestObject) (openapi.UpdateExerciseResponseObject, error) {
	return nil, notImplemented("UpdateExercise")
}

func (Unimplemented) GetLastPerformance(_ context.Context, _ openapi.GetLastPerformanceRequestObject) (openapi.GetLastPerformanceResponseObject, error) {
	return nil, notImplemented("GetLastPerformance")
}

func (Unimplemented) ExportCsv(_ context.Context, _ openapi.ExportCsvRequestObject) (openapi.ExportCsvResponseObject, error) {
	return nil, notImplemented("ExportCsv")
}

func (Unimplemented) ImportCsv(_ context.Context, _ openapi.ImportCsvRequestObject) (openapi.ImportCsvResponseObject, error) {
	return nil, notImplemented("ImportCsv")
}

func (Unimplemented) PullSync(_ context.Context, _ openapi.PullSyncRequestObject) (openapi.PullSyncResponseObject, error) {
	return nil, notImplemented("PullSync")
}

func (Unimplemented) PushSync(_ context.Context, _ openapi.PushSyncRequestObject) (openapi.PushSyncResponseObject, error) {
	return nil, notImplemented("PushSync")
}

func (Unimplemented) ListTemplates(_ context.Context, _ openapi.ListTemplatesRequestObject) (openapi.ListTemplatesResponseObject, error) {
	return nil, notImplemented("ListTemplates")
}

func (Unimplemented) CreateTemplate(_ context.Context, _ openapi.CreateTemplateRequestObject) (openapi.CreateTemplateResponseObject, error) {
	return nil, notImplemented("CreateTemplate")
}

func (Unimplemented) DeleteTemplate(_ context.Context, _ openapi.DeleteTemplateRequestObject) (openapi.DeleteTemplateResponseObject, error) {
	return nil, notImplemented("DeleteTemplate")
}

func (Unimplemented) GetTemplate(_ context.Context, _ openapi.GetTemplateRequestObject) (openapi.GetTemplateResponseObject, error) {
	return nil, notImplemented("GetTemplate")
}

func (Unimplemented) UpdateTemplate(_ context.Context, _ openapi.UpdateTemplateRequestObject) (openapi.UpdateTemplateResponseObject, error) {
	return nil, notImplemented("UpdateTemplate")
}

func (Unimplemented) ListWorkoutSessions(_ context.Context, _ openapi.ListWorkoutSessionsRequestObject) (openapi.ListWorkoutSessionsResponseObject, error) {
	return nil, notImplemented("ListWorkoutSessions")
}

func (Unimplemented) CreateWorkoutSession(_ context.Context, _ openapi.CreateWorkoutSessionRequestObject) (openapi.CreateWorkoutSessionResponseObject, error) {
	return nil, notImplemented("CreateWorkoutSession")
}

func (Unimplemented) DeleteWorkoutSession(_ context.Context, _ openapi.DeleteWorkoutSessionRequestObject) (openapi.DeleteWorkoutSessionResponseObject, error) {
	return nil, notImplemented("DeleteWorkoutSession")
}

func (Unimplemented) GetWorkoutSession(_ context.Context, _ openapi.GetWorkoutSessionRequestObject) (openapi.GetWorkoutSessionResponseObject, error) {
	return nil, notImplemented("GetWorkoutSession")
}

func (Unimplemented) UpdateWorkoutSession(_ context.Context, _ openapi.UpdateWorkoutSessionRequestObject) (openapi.UpdateWorkoutSessionResponseObject, error) {
	return nil, notImplemented("UpdateWorkoutSession")
}

func (Unimplemented) CreateWorkoutSet(_ context.Context, _ openapi.CreateWorkoutSetRequestObject) (openapi.CreateWorkoutSetResponseObject, error) {
	return nil, notImplemented("CreateWorkoutSet")
}

func (Unimplemented) DeleteWorkoutSet(_ context.Context, _ openapi.DeleteWorkoutSetRequestObject) (openapi.DeleteWorkoutSetResponseObject, error) {
	return nil, notImplemented("DeleteWorkoutSet")
}

func (Unimplemented) UpdateWorkoutSet(_ context.Context, _ openapi.UpdateWorkoutSetRequestObject) (openapi.UpdateWorkoutSetResponseObject, error) {
	return nil, notImplemented("UpdateWorkoutSet")
}
