/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description DB 接続を含む疎通確認。Supabase の7日間非アクティブによる
         *     自動停止を回避する keepalive も兼ねる（インフラ設計 §2.1）。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 種目の一覧 */
        get: operations["listExercises"];
        put?: never;
        /**
         * 種目を追加
         * @description 種目マスタ（49種目）はマイグレーションで投入済み。ここでは独自種目を追加する。
         *     既存の種目と同じものを別表記で追加しない。時系列が分断される。
         */
        post: operations["createExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        /** 種目の取得 */
        get: operations["getExercise"];
        put?: never;
        post?: never;
        /** 種目の削除（論理削除） */
        delete: operations["deleteExercise"];
        options?: never;
        head?: never;
        /** 種目の更新 */
        patch: operations["updateExercise"];
        trace?: never;
    };
    "/v1/workout-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** セッションの一覧 */
        get: operations["listWorkoutSessions"];
        put?: never;
        /**
         * セッションの作成（セットを含めて一括登録できる）
         * @description オフラインで記録した内容を一括送信するため、セットを含めて作成できる。
         *     クライアントが生成した UUID を `id` に指定すると冪等に扱われる
         *     （同じ id での再送は 200 を返す）。
         */
        post: operations["createWorkoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** セッションの取得（セットを含む） */
        get: operations["getWorkoutSession"];
        put?: never;
        post?: never;
        /** セッションの削除（論理削除。配下のセットも削除される） */
        delete: operations["deleteWorkoutSession"];
        options?: never;
        head?: never;
        /** セッションの更新 */
        patch: operations["updateWorkoutSession"];
        trace?: never;
    };
    "/v1/workout-sessions/{sessionId}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** セットの追加 */
        post: operations["createWorkoutSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** セットの削除（論理削除） */
        delete: operations["deleteWorkoutSet"];
        options?: never;
        head?: never;
        /** セットの更新 */
        patch: operations["updateWorkoutSet"];
        trace?: never;
    };
    "/v1/exercises/{exerciseId}/last-performance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        /**
         * 前回の実施内容
         * @description 要件 T-02（前回値のデフォルト表示）のためのエンドポイント。
         *     入力速度を決める最重要機能であり、1リクエストで取得できるようにする。
         */
        get: operations["getLastPerformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** テンプレートの一覧 */
        get: operations["listTemplates"];
        put?: never;
        /** テンプレートの作成 */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        /** テンプレートの取得 */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        /** テンプレートの削除（論理削除） */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        /** テンプレートの更新 */
        patch: operations["updateTemplate"];
        trace?: never;
    };
    "/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 差分の取得
         * @description `updatedSince` 以降に変更されたリソースをまとめて返す。
         *     **削除済み（`deletedAt` が設定されたもの）も含む**（ADR-0014）。
         *     クライアントはこれを受けてローカルDBを更新する。
         */
        get: operations["pullSync"];
        put?: never;
        /**
         * ローカルの変更を一括送信
         * @description オフライン中に蓄積した変更をまとめて送る。
         *     サーバは `updatedAt` を比較し、**サーバ側が新しいものはスキップして
         *     `conflicts` に含めて返す**（Last Write Wins / ADR-0014）。
         */
        post: operations["pushSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CSV エクスポート
         * @description `daily.csv` / `workouts.csv` / `measures.csv` と同じスキーマで出力する。
         *     Go 実装の検証基準（`reference/analysis/`）の入力形式であり、
         *     長期バックアップの正でもある（ADR-0002 / ADR-0011）。
         */
        get: operations["exportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CSV インポート
         * @description 要件 I-01。アプリ完成前に CSV で記録した期間のデータを取り込む。
         *     対応するのは本プロジェクトの CSV スキーマのみ。
         */
        post: operations["importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 部位。肩は前部/中部/後部、背中は広背筋/僧帽筋に分ける
         * @enum {string}
         */
        MuscleGroup: "胸" | "広背筋" | "僧帽筋" | "肩前部" | "肩中部" | "肩後部" | "上腕二頭" | "上腕三頭" | "大腿四頭" | "ハム" | "臀部" | "ふくらはぎ" | "腹";
        /**
         * @description 取り込めなかった行。**1行のミスで全部止めない**ので、
         *     読めた行は取り込んだうえでこれを返す（要件 I-01）。
         */
        ImportError: {
            /** @description CSV の行番号（ヘッダが1） */
            line: number;
            message: string;
        };
        /**
         * @description push で適用されなかった変更。サーバ側の `updatedAt` の方が新しい（ADR-0014）。
         *     クライアントは pull し直してから再送する。
         */
        SyncConflict: {
            /** @enum {string} */
            resource: "session" | "set";
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            serverUpdatedAt: string;
        };
        Timestamps: {
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description 競合解決に使う（ADR-0014）
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 論理削除。物理削除しない（ADR-0014）
             */
            deletedAt?: string | null;
        };
        Exercise: components["schemas"]["Timestamps"] & {
            /** Format: uuid */
            id: string;
            /**
             * @description 表記は固定する。ゆれると時系列が分断される
             * @example ベンチプレス
             */
            name: string;
            muscleGroup: components["schemas"]["MuscleGroup"];
            /** @default false */
            isCompound?: boolean;
            defaultRestSec?: number | null;
        };
        ExerciseInput: {
            /**
             * Format: uuid
             * @description クライアント生成の UUID（冪等性のため）
             */
            id?: string;
            name: string;
            muscleGroup: components["schemas"]["MuscleGroup"];
            /** @default false */
            isCompound?: boolean;
            defaultRestSec?: number | null;
        };
        WorkoutSet: components["schemas"]["Timestamps"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            exerciseId: string;
            setNo: number;
            /** @description kg 固定（データモデル参照） */
            weightKg: number;
            reps: number;
            /**
             * @description Reps In Reserve（あと何回できたか）。
             *     **これがないと推定1RMが計算できず進捗が測れない**。
             */
            rir?: number | null;
        };
        WorkoutSetInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sessionId?: string;
            /** Format: uuid */
            exerciseId: string;
            setNo: number;
            weightKg: number;
            reps: number;
            rir?: number | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        WorkoutSession: components["schemas"]["Timestamps"] & {
            /** Format: uuid */
            id: string;
            /**
             * Format: date
             * @description JST の日付（ADR-0013）
             */
            date: string;
            /** Format: uuid */
            templateId?: string | null;
            note?: string | null;
            sets: components["schemas"]["WorkoutSet"][];
        };
        WorkoutSessionInput: {
            /**
             * Format: uuid
             * @description クライアント生成の UUID。再送時は冪等に扱われる
             */
            id?: string;
            /** Format: date */
            date: string;
            /** Format: uuid */
            templateId?: string | null;
            note?: string | null;
            sets?: components["schemas"]["WorkoutSetInput"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        TemplateItem: {
            /** Format: uuid */
            exerciseId: string;
            order: number;
            targetSets: number;
            targetRepsMin?: number | null;
            targetRepsMax?: number | null;
            targetRir?: number | null;
        };
        Template: components["schemas"]["Timestamps"] & {
            /** Format: uuid */
            id: string;
            /** @example Day1 胸 */
            name: string;
            items: components["schemas"]["TemplateItem"][];
        };
        TemplateInput: {
            /** Format: uuid */
            id?: string;
            name: string;
            items: components["schemas"]["TemplateItem"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description RFC 7807 Problem Details */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description バリデーションエラーの詳細 */
            errors?: {
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 認証されていない */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 競合。サーバ側の `updatedAt` がクライアントの保持する値より新しい（ADR-0014）。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description 入力値の検証に失敗（要件 §4.8）。
         *     体重30〜200kg、未来日の禁止、RIR 0〜10 など。
         */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description DB 接続不可など */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ExerciseId: string;
        SessionId: string;
        SetId: string;
        TemplateId: string;
        MuscleGroup: components["schemas"]["MuscleGroup"];
        /** @description 論理削除済みを含めるか。同期用途以外では false */
        IncludeDeleted: boolean;
        /** @description JST の日付（ADR-0013） */
        DateFrom: string;
        DateTo: string;
        Limit: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** Format: date-time */
                        time: string;
                    };
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listExercises: {
        parameters: {
            query?: {
                muscleGroup?: components["parameters"]["MuscleGroup"];
                /** @description 論理削除済みを含めるか。同期用途以外では false */
                includeDeleted?: components["parameters"]["IncludeDeleted"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Exercise"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseInput"];
            };
        };
        responses: {
            /** @description 作成 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWorkoutSessions: {
        parameters: {
            query?: {
                /** @description JST の日付（ADR-0013） */
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["WorkoutSession"][];
                        /** @description 次ページがある場合のカーソル */
                        nextCursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWorkoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionInput"];
            };
        };
        responses: {
            /** @description 既に同じ id で作成済み（冪等） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            /** @description 作成 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getWorkoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteWorkoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWorkoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    date?: string;
                    /** Format: uuid */
                    templateId?: string | null;
                    note?: string | null;
                    /**
                     * Format: date-time
                     * @description クライアントが保持する更新時刻。サーバ側がこれより新しい場合は
                     *     409 を返す（ADR-0014）。
                     */
                    updatedAt?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createWorkoutSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSetInput"];
            };
        };
        responses: {
            /** @description 作成 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSet"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteWorkoutSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWorkoutSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSetInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSet"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getLastPerformance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        exerciseId: string;
                        /**
                         * Format: date
                         * @description 前回実施日。未実施なら null
                         */
                        date?: string | null;
                        sets?: components["schemas"]["WorkoutSet"][];
                        /** @description 前回の推定1RM（Epley + RIR補正） */
                        estimatedOneRm?: number | null;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Template"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateInput"];
            };
        };
        responses: {
            /** @description 作成 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    pullSync: {
        parameters: {
            query: {
                /** @description 前回同期時にサーバが返した `serverTime` を渡す */
                updatedSince: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description 次回の `updatedSince` に使う
                         */
                        serverTime: string;
                        exercises: components["schemas"]["Exercise"][];
                        sessions: components["schemas"]["WorkoutSession"][];
                        sets: components["schemas"]["WorkoutSet"][];
                        templates: components["schemas"]["Template"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    pushSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sessions?: components["schemas"]["WorkoutSessionInput"][];
                    sets?: components["schemas"]["WorkoutSetInput"][];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 適用された件数 */
                        applied: number;
                        /** @description サーバ側が新しく、適用されなかったもの */
                        conflicts: components["schemas"]["SyncConflict"][];
                        /** Format: date-time */
                        serverTime: string;
                    };
                };
            };
        };
    };
    exportCsv: {
        parameters: {
            query: {
                resource: "daily" | "workouts" | "measures";
                /** @description JST の日付（ADR-0013） */
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    importCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @enum {string} */
                    resource: "daily" | "workouts" | "measures";
                    /** Format: binary */
                    file: string;
                    /**
                     * @description 同日・同種目の重複をどう扱うか（要件 I-03）
                     * @default skip
                     * @enum {string}
                     */
                    onDuplicate?: "skip" | "overwrite";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        imported: number;
                        skipped: number;
                        errors: components["schemas"]["ImportError"][];
                    };
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
}
